[package]
name = "dav-xml-client"
version.workspace = true
authors.workspace = true
categories = ["network-programming", "web-programming::http-client"]
edition.workspace = true
homepage.workspace = true
include = ["/README.md", "/src/**"]
keywords = ["webdav", "client", "rfc4918", "dav", "http"]
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
description = "Minimal sync and async WebDAV (RFC 4918) client."

[features]
containers = ["mock"]
default = ["reqwest"]
isahc = ["dep:isahc", "isahc/default-tls", "isahc/http2", "isahc/static-curl"]
mock = []
native-tls = ["reqwest?/native-tls", "ureq?/native-tls"]
reqwest = ["dep:reqwest", "reqwest/default-tls", "reqwest/http2"]
rustls = ["reqwest?/rustls", "ureq?/rustls"]
ureq = ["dep:ureq", "ureq/rustls"]

[dependencies]
bytes = { workspace = true }
dav-xml = { workspace = true }
http = { workspace = true }
httpdate = { workspace = true }
isahc = { workspace = true, optional = true }
mime = { workspace = true }
reqwest = { workspace = true, optional = true }
thiserror = { workspace = true }
time = { workspace = true }
ureq = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serial_test = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[lib]
name = "dav_xml_client"
path = "src/lib.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
