[package]
name = "dav-xml-client"
version.workspace = true
authors.workspace = true
categories = ["network-programming", "web-programming::http-client"]
edition.workspace = true
homepage.workspace = true
include = ["/README.md", "/src/**"]
keywords = ["webdav", "client", "rfc4918", "dav", "http"]
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
description = "Minimal sync and async WebDAV (RFC 4918) client."

[dependencies]
dav-xml = { workspace = true }

[lib]
name = "dav_xml_client"
path = "src/lib.rs"

[lints]
workspace = true
